# https://docs.github.com/en/code-security/supply-chain-security/enabling-and-disabling-version-updates
# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#ignore
version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: "master"
    pull-request-branch-name:
      separator: "-"
