
dist: trusty

language: php
php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - 'nightly'

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.4snapshot'
    - php: 'nightly'

before_script:
  # Install packages
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install -n ;

script:
  # Test all the things
  - vendor/bin/phing

after_script:
  # Track code coverage
  - if [[ -n "$CODACY_PROJECT_TOKEN" ]]; then
        vendor/bin/codacycoverage clover build/coverage/xml ;
    fi
