name: Unit Tests

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        name: PHP ${{ matrix.php-version }}, ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                php-version: ['7.2', '7.3', '7.4']
                # os: [ubuntu-latest, macos-latest, windows-latest]
                os: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v2

            # https://github.com/shivammathur/setup-php
            -
                name: Set up PHP ${{ matrix.php-version }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: mbstring
                    tools: cs2pr

            -
                name: Setup Problem Matchers for PHP
                run: |
                    echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                    echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            -
                name: Validate composer.json and composer.lock
                run: composer validate

            # composer cache
            # https://github.com/actions/cache/blob/master/examples.md#php---composer
            -
                name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -
                name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -
                name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-suggest

            -
                name: Code Standards
                if: matrix.php-version == '7.3' && matrix.os == 'ubuntu-latest'
                # crank the warning severity because cs2pr treats warnings as failures
                run: |
                    vendor/bin/phpcs -q --warning-severity=10 --report=checkstyle | cs2pr

            -
                name: Unit Tests
                run: vendor/bin/phpunit

            -
                name: Static Analysis
                if: matrix.php-version == '7.4' && matrix.os == 'ubuntu-latest'
                run: vendor/bin/phpstan analyse --error-format=checkstyle | sed '/^$/d' | cs2pr
